# Generated by Django 3.2.4 on 2021-06-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_prince_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
